CC = gcc
CFLAGS = -g -Wall -Wextra -Wshadow -Wunused -O3 -std=gnu99 -fPIC -Wno-unused-function -DTESTING_STANDALONE 
INCLUDES = -I/Users/dcroton/Documents/Science/projects/sage-repos/sage-model/src

# Target
TARGET = test_io_memory_map

# Source files
SOURCES = test_io_memory_map.c \
          /Users/dcroton/Documents/Science/projects/sage-repos/sage-model/src/io/io_memory_map.o \
          stubs/logging_stubs.c

# Object files
OBJECTS = $(SOURCES:.c=.o)

# Main target
$(TARGET): $(OBJECTS)
	$(CC) $(CFLAGS) -o $@ $^ -lm

# Compile
%.o: %.c
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@

# Clean
clean:
	rm -f $(TARGET) $(OBJECTS)