# Test makefile for module callback system
CC := clang
CFLAGS := -g -Wall -I../src -I../src/core

# Test programs
TEST_MODULE_CALLBACK := test_module_callback

all: $(TEST_MODULE_CALLBACK)

$(TEST_MODULE_CALLBACK): test_module_callback.c
	$(CC) $(CFLAGS) -o $@ $^ -L.. -lsage -lm

clean:
	rm -f $(TEST_MODULE_CALLBACK)
