
# Makefile for module_dependency tests
#

EXEC   = test_module_dependency

SRC    = test_module_dependency.c

LIBS   = -L.. -lsage -lm -ldl

CFLAGS = -g -O2 -Wall -Wextra -Wpedantic -std=c99
CFLAGS += -DROOT_DIR='"$(shell pwd)/.."'

ifeq (debug,$(findstring debug,$(MAKECMDGOALS)))
CFLAGS += -DDEBUG_MODE
endif

all: $(EXEC)

$(EXEC): $(SRC)
	$(CC) $(CFLAGS) -o $@ $(SRC) $(LIBS)

clean:
	rm -f $(EXEC)

debug: all
