# Test makefile for dynamic library system
CC := clang
CFLAGS := -g -Wall -I../src -I../src/core

# Platform detection for linker flags
UNAME := $(shell uname)
ifeq ($(UNAME), Linux)
    LDFLAGS := -ldl
else
    LDFLAGS :=
endif

# Test programs
TEST_DYNAMIC_LIBRARY := test_dynamic_library

all: $(TEST_DYNAMIC_LIBRARY)

$(TEST_DYNAMIC_LIBRARY): test_dynamic_library.c
	$(CC) $(CFLAGS) -o $@ $^ -L.. -lsage -lm $(LDFLAGS)

clean:
	rm -f $(TEST_DYNAMIC_LIBRARY)
