# Makefile for evolution diagnostics tests
# Part of SAGE model test suite

TEST_SRCS = test_evolution_diagnostics.c
TEST_OBJS = $(TEST_SRCS:.c=.o)
TEST_EXES = test_evolution_diagnostics

# Core files needed for tests
CORE_SRCS = ../src/core/core_evolution_diagnostics.c \
            ../src/core/core_logging.c \
            ../src/core/core_event_system.c \
            ../src/core/core_parameter_views.c \
            ../src/core/core_mymalloc.c

CORE_OBJS = $(CORE_SRCS:.c=.o)

# We need to explicitly compile these objects if they don't exist
../src/core/core_parameter_views.o:
	$(MAKE) -C ../src/core core_parameter_views.o

../src/core/core_mymalloc.o:
	$(MAKE) -C ../src/core core_mymalloc.o

# Compiler flags
CFLAGS += -I.. -g -DUNIT_TESTING -Wall -Wextra

# Rules
all: $(TEST_EXES)

test_evolution_diagnostics: test_evolution_diagnostics.o $(CORE_OBJS)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS) -lm

clean:
	rm -f $(TEST_OBJS) $(TEST_EXES)

.PHONY: all clean