CC          := gcc
GSL_INCL    :=
GSL_LIBS    :=

CFLAGS      := -g -Wall -Wextra -Wshadow -Wunused -O3 -std=gnu99 -fPIC -Wno-unused-function -DTESTING_STANDALONE $(GSL_INCL)
LDFLAGS     := -lm $(GSL_LIBS) 

EXEC        := test_module_parameter

SRC_DIR     := $(realpath $(CURDIR)/../src)
TEST_FILES  := test_module_parameter.c
MODULE_FILES := $(SRC_DIR)/core/core_module_parameter.c $(SRC_DIR)/core/core_logging.c $(SRC_DIR)/core/core_mymalloc.c

OBJ_TEST    := $(TEST_FILES:.c=.o)
OBJ_MODULE  := $(notdir $(MODULE_FILES:.c=.o))
INCLUDES    := -I$(SRC_DIR) -I$(SRC_DIR)/core -I.

all: $(EXEC)

$(EXEC): $(OBJ_TEST) $(OBJ_MODULE)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

%.o: %.c
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@

$(OBJ_MODULE): %.o: $(SRC_DIR)/core/%.c
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@

clean:
	rm -f $(OBJ_TEST) $(OBJ_MODULE) $(EXEC)

run: $(EXEC)
	./$(EXEC)

.PHONY: all clean run