# Makefile for io_validation test
CC := clang
CFLAGS := -g -Wall -I../src -I../src/core -I../src/io -I/opt/homebrew/include
HDFLIB := -L/opt/homebrew/lib -lhdf5 -lz

# IO sources
IO_SRC := ../src/io/io_validation.c \
          ../src/io/io_interface.c

# Core sources
CORE_SRC := ../src/core/core_logging.c \
            ../src/core/core_mymalloc.c \
            ../src/core/core_utils.c

# Test program
TEST_IO_VALIDATION := test_io_validation

all: $(TEST_IO_VALIDATION)

$(TEST_IO_VALIDATION): test_io_validation.c $(IO_SRC) $(CORE_SRC)
	$(CC) $(CFLAGS) -DHDF5 -o $@ $^ $(HDFLIB) -lm

clean:
	rm -f $(TEST_IO_VALIDATION)
