CC          := gcc
GSL_INCL    :=
GSL_LIBS    :=

CFLAGS      := -g -Wall -Wextra -Wshadow -Wunused -O3 -std=gnu99 -fPIC -Wno-unused-function -DTESTING_STANDALONE $(GSL_INCL)
LDFLAGS     := -lm $(GSL_LIBS) 

EXEC        := test_memory_mapping_param

SRC_DIR     := $(realpath $(CURDIR)/../src)
TEST_FILES  := test_memory_mapping_param.c

OBJ_TEST    := $(TEST_FILES:.c=.o)
INCLUDES    := -I$(SRC_DIR)

all: $(EXEC)

$(EXEC): $(OBJ_TEST)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

%.o: %.c
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@

clean:
	rm -f $(OBJ_TEST) $(EXEC)

run: $(EXEC)
	./$(EXEC)

.PHONY: all clean run