/**
 * @file core_properties.c
 * @brief Auto-generated property implementation for SAGE model
 *
 * This file is automatically generated from properties.yaml by
 * generate_property_headers.py. DO NOT EDIT DIRECTLY.
 *
 * Generated on: 2025-05-01 19:33:22
 */

#include "core_allvars.h"
#include "core_properties.h"
#include "core_logging.h"
#include <string.h>
#include <stdlib.h>
#include <assert.h>

/* Property metadata array */
property_meta_t PROPERTY_META[PROP_COUNT] = {
    /* PROP_SnapNum */
    {
        "SnapNum",
        "int32_t",
        "dimensionless",
        "Snapshot number of the galaxy",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_Type */
    {
        "Type",
        "int32_t",
        "dimensionless",
        "Galaxy type (0=central, 1=satellite)",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_GalaxyNr */
    {
        "GalaxyNr",
        "int32_t",
        "dimensionless",
        "Galaxy number within the tree",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_CentralGal */
    {
        "CentralGal",
        "int32_t",
        "dimensionless",
        "Index of the central galaxy in the same FoF group",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_HaloNr */
    {
        "HaloNr",
        "int32_t",
        "dimensionless",
        "Halo number in the tree",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_MostBoundID */
    {
        "MostBoundID",
        "long long",
        "dimensionless",
        "ID of the most bound particle in the subhalo",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_GalaxyIndex */
    {
        "GalaxyIndex",
        "uint64_t",
        "dimensionless",
        "Unique galaxy identifier based on tree local galaxy number, file local tree number and file number",
        true,
        2,
        false,
        0,
        NULL
    },
    /* PROP_CentralGalaxyIndex */
    {
        "CentralGalaxyIndex",
        "uint64_t",
        "dimensionless",
        "Galaxy index of the central galaxy of this galaxy's FoF group",
        true,
        2,
        false,
        0,
        NULL
    },
    /* PROP_mergeType */
    {
        "mergeType",
        "int32_t",
        "dimensionless",
        "Merger type (0=none; 1=minor merger; 2=major merger; 3=disk instability; 4=disrupt to ICS)",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_mergeIntoID */
    {
        "mergeIntoID",
        "int32_t",
        "dimensionless",
        "Galaxy ID that this galaxy merges into",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_mergeIntoSnapNum */
    {
        "mergeIntoSnapNum",
        "int32_t",
        "dimensionless",
        "Snapshot number when the merger occurs",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_dT */
    {
        "dT",
        "float",
        "Gyr",
        "Time step for galaxy evolution",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_Pos */
    {
        "Pos",
        "float[3]",
        "Mpc/h",
        "Position coordinates (x,y,z)",
        true,
        0,
        true,
        3,
        NULL
    },
    /* PROP_Vel */
    {
        "Vel",
        "float[3]",
        "km/s",
        "Velocity components (vx,vy,vz)",
        true,
        0,
        true,
        3,
        NULL
    },
    /* PROP_Len */
    {
        "Len",
        "int",
        "dimensionless",
        "Number of particles in the halo",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_Mvir */
    {
        "Mvir",
        "float",
        "1e10 Msun/h",
        "Virial mass of the halo",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_deltaMvir */
    {
        "deltaMvir",
        "float",
        "1e10 Msun/h",
        "Change in virial mass since last snapshot",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_CentralMvir */
    {
        "CentralMvir",
        "float",
        "1e10 Msun/h",
        "Virial mass of the central subhalo",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_Rvir */
    {
        "Rvir",
        "float",
        "Mpc/h",
        "Virial radius",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_Vvir */
    {
        "Vvir",
        "float",
        "km/s",
        "Virial velocity",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_Vmax */
    {
        "Vmax",
        "float",
        "km/s",
        "Maximum circular velocity",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_ColdGas */
    {
        "ColdGas",
        "float",
        "1e10 Msun/h",
        "Cold gas mass in the disk",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_StellarMass */
    {
        "StellarMass",
        "float",
        "1e10 Msun/h",
        "Total stellar mass (disk + bulge)",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_BulgeMass */
    {
        "BulgeMass",
        "float",
        "1e10 Msun/h",
        "Stellar mass in the bulge",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_HotGas */
    {
        "HotGas",
        "float",
        "1e10 Msun/h",
        "Hot gas mass in the halo",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_EjectedMass */
    {
        "EjectedMass",
        "float",
        "1e10 Msun/h",
        "Gas mass ejected by feedback",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_BlackHoleMass */
    {
        "BlackHoleMass",
        "float",
        "1e10 Msun/h",
        "Black hole mass",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_ICS */
    {
        "ICS",
        "float",
        "1e10 Msun/h",
        "Intracluster stars mass",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_MetalsColdGas */
    {
        "MetalsColdGas",
        "float",
        "1e10 Msun/h",
        "Metal mass in cold gas",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_MetalsStellarMass */
    {
        "MetalsStellarMass",
        "float",
        "1e10 Msun/h",
        "Metal mass in stars",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_MetalsBulgeMass */
    {
        "MetalsBulgeMass",
        "float",
        "1e10 Msun/h",
        "Metal mass in bulge",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_MetalsHotGas */
    {
        "MetalsHotGas",
        "float",
        "1e10 Msun/h",
        "Metal mass in hot gas",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_MetalsEjectedMass */
    {
        "MetalsEjectedMass",
        "float",
        "1e10 Msun/h",
        "Metal mass in ejected gas",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_MetalsICS */
    {
        "MetalsICS",
        "float",
        "1e10 Msun/h",
        "Metal mass in intracluster stars",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_SfrDisk */
    {
        "SfrDisk",
        "float[STEPS]",
        "Msun/yr",
        "Star formation rate in disk for each timestep",
        true,
        0,
        true,
        STEPS,
        NULL
    },
    /* PROP_SfrBulge */
    {
        "SfrBulge",
        "float[STEPS]",
        "Msun/yr",
        "Star formation rate in bulge for each timestep",
        true,
        0,
        true,
        STEPS,
        NULL
    },
    /* PROP_SfrDiskColdGas */
    {
        "SfrDiskColdGas",
        "float[STEPS]",
        "1e10 Msun/h",
        "Cold gas mass during disk star formation for each timestep",
        true,
        0,
        true,
        STEPS,
        NULL
    },
    /* PROP_SfrDiskColdGasMetals */
    {
        "SfrDiskColdGasMetals",
        "float[STEPS]",
        "1e10 Msun/h",
        "Cold gas metals during disk star formation for each timestep",
        true,
        0,
        true,
        STEPS,
        NULL
    },
    /* PROP_SfrBulgeColdGas */
    {
        "SfrBulgeColdGas",
        "float[STEPS]",
        "1e10 Msun/h",
        "Cold gas mass during bulge star formation for each timestep",
        true,
        0,
        true,
        STEPS,
        NULL
    },
    /* PROP_SfrBulgeColdGasMetals */
    {
        "SfrBulgeColdGasMetals",
        "float[STEPS]",
        "1e10 Msun/h",
        "Cold gas metals during bulge star formation for each timestep",
        true,
        0,
        true,
        STEPS,
        NULL
    },
    /* PROP_StarFormationHistory */
    {
        "StarFormationHistory",
        "float[]",
        "Msun/yr",
        "Complete star formation history for all output snapshots",
        true,
        0,
        true,
        0,
        "simulation.NumSnapOutputs"
    },
    /* PROP_DiskScaleRadius */
    {
        "DiskScaleRadius",
        "float",
        "Mpc/h",
        "Scale radius of the stellar disk",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_MergTime */
    {
        "MergTime",
        "float",
        "Gyr",
        "Time until merger",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_Cooling */
    {
        "Cooling",
        "double",
        "erg/s",
        "Cooling energy rate",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_Heating */
    {
        "Heating",
        "double",
        "erg/s",
        "Heating energy rate (from AGN)",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_r_heat */
    {
        "r_heat",
        "float",
        "Mpc/h",
        "Heating radius for AGN feedback",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_QuasarModeBHaccretionMass */
    {
        "QuasarModeBHaccretionMass",
        "float",
        "1e10 Msun/h",
        "Mass accreted by black hole in quasar mode",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_TimeOfLastMajorMerger */
    {
        "TimeOfLastMajorMerger",
        "float",
        "Gyr",
        "Time of last major merger",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_TimeOfLastMinorMerger */
    {
        "TimeOfLastMinorMerger",
        "float",
        "Gyr",
        "Time of last minor merger",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_OutflowRate */
    {
        "OutflowRate",
        "float",
        "Msun/yr",
        "Outflow rate from feedback",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_TotalSatelliteBaryons */
    {
        "TotalSatelliteBaryons",
        "float",
        "1e10 Msun/h",
        "Total baryon mass in satellites",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_infallMvir */
    {
        "infallMvir",
        "float",
        "1e10 Msun/h",
        "Virial mass at infall",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_infallVvir */
    {
        "infallVvir",
        "float",
        "km/s",
        "Virial velocity at infall",
        true,
        0,
        false,
        0,
        NULL
    },
    /* PROP_infallVmax */
    {
        "infallVmax",
        "float",
        "km/s",
        "Maximum circular velocity at infall",
        true,
        0,
        false,
        0,
        NULL
    }
};

/* Support function for dynamic array sizing */
/**
 * @brief Fetch NumSnapOutputs parameter for sizing dynamic arrays
 * @return Number of snapshot outputs or a default value
 */
int fetch_NumSnapOutputs(void) 
{
    /* Use a default value for now - will be replaced with actual parameter in future */
    return 100;
}

/**
 * @brief Initialize the property system
 */
int initialize_property_system(void)
{
    LOG_DEBUG("Initializing property system with %d properties", PROP_COUNT);
    /* Dynamic size determination happens here */
    /* Set up dynamic array sizes */
    /* Handle size parameter: simulation.NumSnapOutputs */
    extern int fetch_NumSnapOutputs(void); /* Forward declaration */
    int NumSnapOutputs_size = fetch_NumSnapOutputs();
    LOG_DEBUG("Setting StarFormationHistory array size to %d", NumSnapOutputs_size);
    return 0;
}

/**
 * @brief Clean up the property system resources
 */
void cleanup_property_system(void)
{
    LOG_DEBUG("Cleaning up property system");
    /* Cleanup any allocated memory for the property system */
}

/**
 * @brief Allocate property memory for a galaxy
 */
int allocate_galaxy_properties(struct GALAXY *g)
{
    if (g == NULL) {
        LOG_ERROR("Cannot allocate properties for NULL galaxy pointer");
        return -1;
    }
    
    /* Allocate the property structure */
    g->properties = (galaxy_properties_t *)calloc(1, sizeof(galaxy_properties_t));
    if (g->properties == NULL) {
        LOG_ERROR("Failed to allocate galaxy properties structure");
        return -1;
    }
    
    /* Allocate memory for dynamic arrays */
    /* Allocate StarFormationHistory array */
    if (PROPERTY_META[PROP_StarFormationHistory].size_parameter != NULL) {
        /* Size determined from parameter at initialization */
        int size = g->properties->StarFormationHistory_size;
        if (size > 0) {
            g->properties->StarFormationHistory = (float *)calloc(size, sizeof(float));
            if (g->properties->StarFormationHistory == NULL) {
                LOG_ERROR("Failed to allocate memory for StarFormationHistory property");
                return -1;
            }
            
            /* Initialize array with default value */
            for (int i = 0; i < size; i++) {
                g->properties->StarFormationHistory[i] = 0.0;
            }
        }
    }
    
    return 0;
}

/**
 * @brief Free property memory for a galaxy
 */
void free_galaxy_properties(struct GALAXY *g)
{
    if (g == NULL || g->properties == NULL) {
        return;
    }
    
    /* Free dynamic arrays */
    /* Free StarFormationHistory array */
    if (g->properties->StarFormationHistory != NULL) {
        free(g->properties->StarFormationHistory);
        g->properties->StarFormationHistory = NULL;
        g->properties->StarFormationHistory_size = 0;
    }
    
    /* Free the property structure itself */
    free(g->properties);
    g->properties = NULL;
}

/**
 * @brief Copy all properties from source galaxy to destination galaxy
 */
int copy_galaxy_properties(struct GALAXY *dest, const struct GALAXY *src)
{
    if (dest == NULL || src == NULL) {
        LOG_ERROR("NULL galaxy pointer in property copy");
        return -1;
    }
    
    /* Free existing destination properties if present */
    free_galaxy_properties(dest);
    
    /* Allocate new properties */
    if (allocate_galaxy_properties(dest) != 0) {
        return -1;
    }
    
    /* Copy fixed-size fields */
    /* Copy the basic structure */
    memcpy(dest->properties, src->properties, sizeof(galaxy_properties_t));

    /* Reset dynamic array pointers to NULL to avoid double-free issues */    dest->properties->StarFormationHistory = NULL;

    /* Copy dynamic arrays */
    /* Copy StarFormationHistory array */
    if (src->properties->StarFormationHistory != NULL && src->properties->StarFormationHistory_size > 0) {
        int size = src->properties->StarFormationHistory_size;
        dest->properties->StarFormationHistory = (float *)malloc(size * sizeof(float));
        if (dest->properties->StarFormationHistory == NULL) {
            LOG_ERROR("Failed to allocate memory for StarFormationHistory property during copy");
            return -1;
        }
        dest->properties->StarFormationHistory_size = size;
        memcpy(dest->properties->StarFormationHistory, src->properties->StarFormationHistory, size * sizeof(float));
    }
    
    return 0;
}

/**
 * @brief Reset properties to initial values
 */
void reset_galaxy_properties(struct GALAXY *g)
{
    if (g == NULL || g->properties == NULL) {
        LOG_ERROR("Cannot reset properties for NULL galaxy or property pointer");
        return;
    }
    
    /* Reset fixed properties to initial values */
    g->properties->SnapNum = -1;
    g->properties->Type = 0;
    g->properties->GalaxyNr = 0;
    g->properties->CentralGal = -1;
    g->properties->HaloNr = -1;
    g->properties->MostBoundID = -1;
    g->properties->GalaxyIndex = 0;
    g->properties->CentralGalaxyIndex = 0;
    g->properties->mergeType = 0;
    g->properties->mergeIntoID = -1;
    g->properties->mergeIntoSnapNum = -1;
    g->properties->dT = 0.0f;
    g->properties->Pos[0] = 0.0f;
    g->properties->Pos[1] = 0.0f;
    g->properties->Pos[2] = 0.0f;
    g->properties->Vel[0] = 0.0f;
    g->properties->Vel[1] = 0.0f;
    g->properties->Vel[2] = 0.0f;
    g->properties->Len = 0;
    g->properties->Mvir = 0.0f;
    g->properties->deltaMvir = 0.0f;
    g->properties->CentralMvir = 0.0f;
    g->properties->Rvir = 0.0f;
    g->properties->Vvir = 0.0f;
    g->properties->Vmax = 0.0f;
    g->properties->ColdGas = 0.0f;
    g->properties->StellarMass = 0.0f;
    g->properties->BulgeMass = 0.0f;
    g->properties->HotGas = 0.0f;
    g->properties->EjectedMass = 0.0f;
    g->properties->BlackHoleMass = 0.0f;
    g->properties->ICS = 0.0f;
    g->properties->MetalsColdGas = 0.0f;
    g->properties->MetalsStellarMass = 0.0f;
    g->properties->MetalsBulgeMass = 0.0f;
    g->properties->MetalsHotGas = 0.0f;
    g->properties->MetalsEjectedMass = 0.0f;
    g->properties->MetalsICS = 0.0f;
    for (int i = 0; i < STEPS; i++) {
        g->properties->SfrDisk[i] = 0.0f;
    }
    for (int i = 0; i < STEPS; i++) {
        g->properties->SfrBulge[i] = 0.0f;
    }
    for (int i = 0; i < STEPS; i++) {
        g->properties->SfrDiskColdGas[i] = 0.0f;
    }
    for (int i = 0; i < STEPS; i++) {
        g->properties->SfrDiskColdGasMetals[i] = 0.0f;
    }
    for (int i = 0; i < STEPS; i++) {
        g->properties->SfrBulgeColdGas[i] = 0.0f;
    }
    for (int i = 0; i < STEPS; i++) {
        g->properties->SfrBulgeColdGasMetals[i] = 0.0f;
    }
    g->properties->DiskScaleRadius = 0.0f;
    g->properties->MergTime = 0.0f;
    g->properties->Cooling = 0.0;
    g->properties->Heating = 0.0;
    g->properties->r_heat = 0.0f;
    g->properties->QuasarModeBHaccretionMass = 0.0f;
    g->properties->TimeOfLastMajorMerger = 0.0f;
    g->properties->TimeOfLastMinorMerger = 0.0f;
    g->properties->OutflowRate = 0.0f;
    g->properties->TotalSatelliteBaryons = 0.0f;
    g->properties->infallMvir = 0.0f;
    g->properties->infallVvir = 0.0f;
    g->properties->infallVmax = 0.0f;
}

/**
 * @brief Get property name string for a property ID
 */
const char* get_property_name(property_id_t id)
{
    if (id >= 0 && id < PROP_COUNT) {
        return PROPERTY_META[id].name;
    }
    return NULL;
}

/**
 * @brief Get property ID for a property name
 */
property_id_t get_property_id(const char *name)
{
    if (name == NULL) {
        return PROP_COUNT;
    }
    
    for (int i = 0; i < PROP_COUNT; i++) {
        if (strcmp(PROPERTY_META[i].name, name) == 0) {
            return (property_id_t)i;
        }
    }
    
    return PROP_COUNT;
}

/* Additional helper functions for property system */
/**
 * @brief Set the size of the StarFormationHistory dynamic array
 * @param g Galaxy pointer
 * @param size New size for the array
 * @return 0 on success, non-zero on failure
 */
int galaxy_set_StarFormationHistory_size(struct GALAXY *g, int size)
{
    if (g == NULL || g->properties == NULL) {
        LOG_ERROR("Cannot set size for NULL galaxy or property pointer");
        return -1;
    }
    
    if (size < 0) {
        LOG_ERROR("Cannot set negative size for StarFormationHistory array");
        return -1;
    }
    
    /* Free existing array if present */
    if (g->properties->StarFormationHistory != NULL) {
        free(g->properties->StarFormationHistory);
        g->properties->StarFormationHistory = NULL;
    }
    
    /* Set new size */
    g->properties->StarFormationHistory_size = size;
    
    /* Allocate new array if size > 0 */
    if (size > 0) {
        g->properties->StarFormationHistory = (float *)calloc(size, sizeof(float));
        if (g->properties->StarFormationHistory == NULL) {
            LOG_ERROR("Failed to allocate memory for StarFormationHistory array");
            g->properties->StarFormationHistory_size = 0;
            return -1;
        }
    }
    
    return 0;
}
